theme = "hugo-theme-nix"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Donovan Lampa's personal site"

[params]
  StackExchangeID = "1176249"
  StackOverflowID = "1152219"
  GithubID = "lampad"
  TwitterID = "donovanlampa"
  LinkedInID = "donovan-lampa-8b17a72b"
  Name = "Donovan Lampa"
  HeaderUsername = "lampad"
  HeaderHostname = "localhost"
  Email = "donovan.lampa@gmail.com"
#  Phone = "+1-972-467-1704"
  Mobile = "+1-972-467-1704"
  About = "Software Engineer. When not writing code can be found gaming, reading, cooking, baking and just generally existing."
  ProfilePicture = "https://scontent-dfw5-1.xx.fbcdn.net/v/t1.0-9/29595323_1903512039722483_6291107755620619602_n.jpg?_nc_cat=0&oh=5c47581330dfcd8f3f18d5ae4c7273f4&oe=5B289E4D"
#  GoogleAnalytics = "your_google_analytics_id"
#  SlackURL = "https://join.slack.com/..."
#  PayPalMeID = "https://www.paypal.me/..."
#  XingURL = "https://www.xing.com/profile/..."

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "./posts"